### ISSUE TITLE
which() function needs to call os.path.basename

### ISSUE THREAD

**Issue by bredeson** [abmudd/Phylogeny#1]
Hey,

I was trying to run your pipeline on the test dataset and it got hung up trying to verify the location and executability of the other scripts packaged with this repo. The `which()` function in `Phylogeny/bin/makephylogenysh.py` fails when the input executable name is prefixed with a relative path (e.g., `../Phylogeny/bin/allgenesingb.py`) and returns `None`. I extracted the function and put it in its own script to test.

```sh
bredeson|21:57:42|workdir> cat which.py 
import os
import sys

def which(pgm):
    path=os.getenv('PATH')
    for p in path.split(os.path.pathsep):
        p=os.path.join(p,pgm)
        if os.path.exists(p) and os.access(p,os.X_OK):
            return p


print(which(sys.argv[1]))

bredeson|22:23:25|workdir> python ./which.py ../Phylogeny/bin/allgenesingb.py
None
bredeson|22:23:37|workdir> python ./which.py allgenesingb.py
/path/to/Phylogeny/bin/allgenesingb.py
bredeson|22:23:45|workdir> python ./which.py /path/to/Phylogeny/bin/allgenesingb.py
/path/to/Phylogeny/bin/allgenesingb.py
```

Hope this helps!

**Comment by abmudd** [comment]
I've updated the `which()` function in the latest commit. Relative paths should work now. If you still have an issue with this, please let me know.
